version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq_data:/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  app:
    build:
      context: .
      dockerfile: CurrencyConverter.Core/Dockerfile
    ports:
      - "5000:80"
    environment:
      - Redis__ConnectionString=redis:6379
      - Seq__ServerUrl=http://seq:80
      - OpenTelemetry__Endpoint=http://jaeger:4317
    depends_on:
      - redis
      - seq
      - jaeger

volumes:
  redis_data:
  seq_data: 