version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq_data:/data

  app:
    build:
      context: .
      dockerfile: CurrencyConverter.Core/Dockerfile
    ports:
      - "5000:80"
    environment:
      - Redis__ConnectionString=redis:6379
      - Seq__ServerUrl=http://seq:80
    depends_on:
      - redis
      - seq

volumes:
  redis_data:
  seq_data: 