version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: CurrencyConverter.Core/Dockerfile
    ports:
      - "5000:80"
    environment:
      - Redis__ConnectionString=redis:6379
    depends_on:
      - redis

volumes:
  redis_data: 